# Generated by Django 3.2 on 2021-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210401_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=5)),
                ('click_count', models.CharField(max_length=30)),
            ],
        ),
    ]
