# Generated by Django 3.2 on 2021-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
