# Generated by Django 3.1.7 on 2021-04-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='asd123', max_length=100),
            preserve_default=False,
        ),
    ]
