# Generated by Django 3.1.7 on 2021-05-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210524_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cart',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order_v2'),
        ),
    ]
